# Site Settings
title:               Destripando Linux
tagline:             a minimalist Jekyll theme
description:
baseurl:            #"/MrRastayoung.github.io"
url:                #"https://mrrastayoung.github.io"
github:
  url:               #"https://mrrastayoung.github.io"
author:
  name:              "Altair"
  email:             "altair.trabajo@gmail.com"
  twitter:           "altairisx"
  instagram:         "altairisx"
  github:            "MrRastayoung"
  facebook:          "altairisx"
  linkedin:          "altairisx"
navigation:
- title: About
  url: /about
- title: Entradas
  url: /blog
- title: Contact
  url: /contact
- title: Raspberry
  url: /raspberry

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
